export default [
  { path: '/carousel', name: 'carousel', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/carousel/index.vue') },
  { path: '/numGrow', name: 'numGrow', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/numGrow/index.vue') },
  { path: '/specialBotton', name: 'specialBotton', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/specialBotton/index.vue') },
  { path: '/arrow', name: 'arrow', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/arrow/index.vue') },
  { path: '/buttery', name: 'buttery', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/buttery/index.vue') },
  { path: '/slide', name: 'slide', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/slide/index.vue') },
  { path: '/countDown', name: 'countDown', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/countDown/index.vue') },
  { path: '/guidePoint', name: 'guidePoint', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/guidePoint/index.vue') },
  { path: '/typeWord', name: 'typeWord', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/typeWord/index.vue') },
  { path: '/useAnimate', name: 'useAnimate', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/useAnimate/index.vue') },
  { path: '/textStreamer', name: 'textStreamer', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/textStreamer/index.vue')},
  { path: '/wordsCarousel', name: 'wordsCarousel', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/wordsCarousel/index.vue')},
  { path: '/textSweat', name: 'textSweat', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/textSweat/index.vue')},
  { path: '/carouselX', name: 'carouselX', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/carouselX/index.vue')},
  { path: '/aniDelay', name: 'aniDelay', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/aniDelay/index.vue')},
  { path: '/textStaggered', name: 'textStaggered', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/textStaggered/index.vue')},
  { path: '/specialBorder', name: 'specialBorder', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/specialBorder/index.vue')},
  { path: '/pieChart', name: 'pieChart', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/pieChart/index.vue')},
  { path: '/redPacket', name: 'redPacket', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/redPacket/index.vue')},
]