export const css3Ani = [
  { path: '/carousel', name: 'carousel', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/carousel/index.vue') },
  { path: '/numGrow', name: 'numGrow', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/numGrow/index.vue') },
  { path: '/breath', name: 'breath', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/breath/index.vue') },
  { path: '/arrow', name: 'arrow', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/arrow/index.vue') },
  { path: '/buttery', name: 'buttery', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/buttery/index.vue') },
  { path: '/slide', name: 'slide', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/slide/index.vue') },
  { path: '/countDown', name: 'countDown', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/countDown/index.vue') },
  { path: '/guidePoint', name: 'guidePoint', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/guidePoint/index.vue') },
  { path: '/typeWord', name: 'typeWord', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/typeWord/index.vue') },
  { path: '/useAnimate', name: 'useAnimate', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/useAnimate/index.vue') },
  { path: '/textStreamer', name: 'textStreamer', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/textStreamer/index.vue')},
  { path: '/wordsCarousel', name: 'wordsCarousel', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/wordsCarousel/index.vue')},
  { path: '/textSweat', name: 'textSweat', component: () => import(/* webpackChunkName: "css3Ani" */ '../../views/css3Ani/textSweat/index.vue')},
]